[theme]
base = "dark"
primaryColor = "#818CF8"
backgroundColor = "#09090B"
secondaryBackgroundColor = "#18181B"
textColor = "#FAFAFA"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
